name: Test Workflow

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python main.py
    - name: Display variables
      run: |-
        echo "CI: $CI"
