name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: src/python main.py
    - name: create pull request
      run: gh pr create --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
