name: Test Workflow

on:
  push:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python src/main.py
    - name: Commit & Push
      run: |-
        git checkout -b branch_to_merge
        git diff
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Zerodha Portfolio Stocks : Updated Content via GitHub Actions Bot" || exit 0
        git push
    - name: create pull request
      run: gh pr create --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
